name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  name: "rsp-manageddevopspool"

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - HarpDataSync/**
      - HarpDataSyncTest/**

parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - datawarehouse
      - systemtest_manual
      - systemtest_auto
      - uat
      - pre_prod
      - production

  - name: devops_library_branch
    displayName: DevOps Library Branch
    type: string
    default: main

  - name: run_sonarcloud_analysis
    displayName: Run Sonar Cloud Analysis
    type: boolean
    default: true

  - name: skip_deployment
    displayName: Skip Deployment
    type: boolean
    default: true

variables:
  - name: vstsFeed
    value: "0e030eb0-cb72-4f42-b99a-26e6544271c3/0a3e0ad2-23b6-4e8b-ae12-cd6d01fe97e7"
  - name: solution
    value: "**/*.sln"
  - name: project
    value: "**/*.csproj"
  - name: projectForContainerBuild
    value: "HarpDataSync.csproj"
  - name: buildConfiguration
    value: "Release"
  - name: service_connection
    ${{ if eq(parameters.env, 'datawarehouse') }}:
      value: "ARM Connection DW"
    ${{ if eq(parameters.env, 'dev') }}:
      value: "ARM Dev Connection New"
    ${{ if eq(parameters.env, 'systemtest_auto') }}:
      value: "ARM Automated Test Connection"  
    ${{ if eq(parameters.env, 'systemtest_manual') }}:
      value: "ARM Manual Test Connection"
    ${{ if eq(parameters.env, 'uat') }}:
        value: "ARM UAT Connection"
    ${{ if eq(parameters.env, 'pre_prod') }}:
        value: "ARM PreProd Connection"
    ${{ if eq(parameters.env, 'production') }}:
        value: "ARM Production Connection" 

  - name: appSettingsJson
    value: |
      [
        {
          "name": "AppSettings__AzureAppConfiguration__Endpoint",
          "value": "$(AppConfigurationEndpoint)",
          "slotSetting": false
        },
        {
          "name": "AppSettings__AzureAppConfiguration__IdentityClientID",
          "value": "$(AppConfigurationClientID)",
          "slotSetting": false
        },
        {
          "name": "HARPSyncTimerSchedule",
          "value": "$(HARPSyncTimerSchedule)",
          "slotSetting": false
        }
      ]

resources:
  repositories:
    - repository: library
      type: github
      name: 'HealthResearchAuthority/rsp-azure-devops-library'
      endpoint: AzureDevOpsToGitHubConnection
      ref: ${{ parameters.devops_library_branch }}

stages:
  - stage: Build
    displayName: "Build Stage"
    condition: and(eq('${{ parameters.env }}', 'dev'), eq('${{ parameters.skip_deployment }}', 'true'))
    jobs:
      - template: jobs/build.yaml@library
        parameters:
          run_github_security_scan: false
          sonar_project_key: HealthResearchAuthority_rsp-harp-data-sync-function
          sonar_project_name: rsp-harp-data-sync-function
          run_sonarcloud_analysis: ${{ parameters.run_sonarcloud_analysis }}

  - stage: DataWarehouse
    displayName: "Deploy to DataWarehouse"
    variables:
      - group: 'DataWarehouseEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync"
    condition: and(eq('${{ parameters.env }}', 'datawarehouse'), eq('${{ parameters.skip_deployment }}', 'false'))
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)

  - stage: dev
    displayName: "Deploy to Development"
    variables: 
      - group: 'DevelopmentEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync-dev"
    condition: and(eq('${{ parameters.env }}', 'dev'), eq('${{ parameters.skip_deployment }}', 'false'))
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)
          
  - stage: systemtest_auto
    variables: 
      - group: 'STAutoEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync-automationtest"
    condition: eq('${{ parameters.env }}', 'systemtest_auto')
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)
          
  - stage: systemtest_manual
    variables: 
      - group: 'STManualEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync-manualtest"
    condition: eq('${{ parameters.env }}', 'systemtest_manual')
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)

  - stage: uat
    displayName: "Deploy to UAT"
    variables: 
      - group: 'UATEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync-uat"
    condition: and(eq('${{ parameters.env }}', 'uat'), eq('${{ parameters.skip_deployment }}', 'false'))
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)

  - stage: pre_prod
    displayName: "Deploy to PreProd"
    variables: 
      - group: 'PreProdEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync-preprod"
    condition: and(eq('${{ parameters.env }}', 'pre_prod'), eq('${{ parameters.skip_deployment }}', 'false'))
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)

  - stage: production
    displayName: "Deploy to Prod"
    variables: 
      - group: 'ProductionEnvironment'
      - name: FunctionAppName
        value: "func-harp-data-sync-prod"
    condition: and(eq('${{ parameters.env }}', 'production'), eq('${{ parameters.skip_deployment }}', 'false'))
    jobs:
      - template: jobs/deployFunction.yaml@library
        parameters:
          appSettings: $(appSettingsJson)
